swagger: "2.0"
info:
  description: "This is the super-duper theme app API"
  version: "1.0.0"
  title: "Super-Duper Theme App"
basePath: "/v2"
tags:
- name: "theme"
schemes:
- "https"
- "http"
paths:
  /theme:
    post:
      tags:
      - "theme"
      summary: "Add a new theme to the store"
      description: ""
      operationId: "addTheme"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Theme object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Theme"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
      - "theme"
      summary: "Update an existing theme"
      description: ""
      operationId: "updateTheme"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Theme object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Theme"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Theme not found"
        "405":
          description: "Validation exception"
  /theme/{themeId}:
    get:
      tags:
      - "theme"
      summary: "Find theme by ID"
      description: "Returns a single theme"
      operationId: "getThemeById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "themeId"
        in: "path"
        description: "ID of theme to return"
        required: true
        type: "integer"
        format: "int"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Theme"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Theme not found"
    delete:
      tags:
      - "theme"
      summary: "Deletes a theme"
      description: ""
      operationId: "deleteTheme"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "themeId"
        in: "path"
        description: "Theme id to delete"
        required: true
        type: "integer"
        format: "int"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Theme not found"
definitions:
  Theme:
    type: "object"
    required:
    - "name"
    - "background-color"
    - "text-color"
    - "primary-button-color"
    - "secondary-button-color"
    properties:
      id:
        type: "integer"
        format: "int"
      name:
        type: "string"
        example: "Dark Theme"
      background-color:
        type: "string"
        example: "#1F2A32"
      primary-text-color:
        type: "string"
        example: "#FFFFFF"
      secondary-text-color:
        type: "string"
        example: "#000000"
      accent-color:
        type: "string"
        example: "#007C7E"
    xml:
      name: "theme"